export const rows = [
  "ones",
  "twos",
  "threes",
  "fours",
  "fives",
  "sixes",
  "upperTotal",
  "bonus",
  "pair",
  "twoPairs",
  "threeOfAKind",
  "fourOfAKind",
  "smallStraight",
  "largeStraight",
  "fullHouse",
  "chance",
  "yatzy",
  "gameTotal",
];
export const nonEditableCells = ["upperTotal", "bonus", "gameTotal"];
export const maxScoresPerRow: Record<string, number> = {
  ones: 5,
  twos: 10,
  threes: 15,
  fours: 20,
  fives: 25,
  sixes: 30,
  pair: 12,
  twoPairs: 22,
  threeOfAKind: 18,
  fourOfAKind: 24,
  smallStraight: 15,
  largeStraight: 20,
  fullHouse: 28,
  chance: 30,
  yatzy: 50,
};
